<?php

namespace File\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
	public function getTotalBySemester($semester)
	{
		$qb = $this->createQueryBuilder('d')
				->where('d.semester = :semester')
				->setParameter('semester', $semester)
				->select('COUNT(d)');

		return (int) $qb->getQuery()
				->getSingleScalarResult();	// Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
	}
	
	public function getTotalBySType($semester, $type)
	{
		$qb = $this->createQueryBuilder('d')
				->where('d.semester = :semester')
				->setParameter('semester', $semester)
				->andwhere('d.type = :type')
				->setParameter('type', $type)
				->select('COUNT(d)');

		return (int) $qb->getQuery()
				->getSingleScalarResult();	// Utilisation de getSingleScalarResult pour avoir directement le résultat du COUNT
	}
}